jwt:
    accessSecretKey: "securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure"
    accessTokenPrefix: "Bearer "
    accessTokenExpirationInHours: 1
    refreshSecretKey: "securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure"
    refreshTokenPrefix: "Refresher "
    refreshTokenExpirationInDays: 2
